export const ADD_BLOG_REQUEST = "ADD_BLOG_REQUEST"
export const ADD_BLOG_REQUEST_SUUCESS = "ADD_BLOG_REQUEST_SUUCESS"
export const ADD_BLOG_REQUEST_FAIL = "ADD_BLOG_REQUEST_FAIL"



export const GET_ALL_BLOG_REQUEST = "GET_ALL_BLOG_REQUEST"
export const GET_ALL_BLOG_REQUEST_SUUCESS = "GET_ALL_BLOG_REQUEST_SUUCESS"
export const GET_ALL_BLOG_REQUEST_FAIL = "GET_ALL_BLOG_REQUEST_FAIL"


export const SINGLE_BLOG_REQUEST = "SINGLE_BLOG_REQUEST";
export const SINGLE_BLOG_REQUEST_SUCCESS = "SINGLE_BLOG_REQUEST_SUCCESS";
export const SINGLE_BLOG_REQUEST_FAIL = "SINGLE_BLOG_REQUEST_FAIL";


export const GET_MY_BLOG_REQUEST = "GET_MY_BLOG_REQUEST"
export const GET_MY_BLOG_REQUEST_SUUCESS = "GET_MY_BLOG_REQUEST_SUUCESS"
export const GET_MY_BLOG_REQUEST_FAIL = "GET_MY_BLOG_REQUEST_FAIL"

export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST"
export const UPDATE_BLOG_REQUEST_SUCCESS = "UPDATE_BLOG_REQUEST_SUCCESS"
export const UPDATE_BLOG_REQUEST_FAIL = "UPDATE_BLOG_REQUEST_FAIL"


export const DELETE_BLOG_RQEUST = "DELETE_BLOG_RQEUST"
export const DELETE_BLOG_RQEUST_SUCCESS = "DELETE_BLOG_RQEUST_SUCCESS"
export const DELETE_BLOG_RQEUST_FAIL = "DELETE_BLOG_RQEUST_FAIL"

