export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS"
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL"


export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_REQUEST_SUCCESS = "SIGNUP_REQUEST_SUCCESS"
export const SIGNUP_REQUEST_FAIL = "SIGNUP_REQUEST_FAIL"


export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST"
export const GET_ALL_USER_REQUEST_SUCCESS = "GET_ALL_USER_REQUEST_SUCCESS"
export const GET_ALL_USER_REQUEST_FAIL = "GET_ALL_USER_REQUEST_FAIL"

export const USER_ADMIN_REQUEST = "USER_ADMIN_REQUEST"
export const USER_ADMIN_REQUEST_SUCCESS = "USER_ADMIN_REQUEST_SUCCESS"
export const USER_ADMIN_REQUEST_FAIL = "USER_ADMIN_REQUEST_FAIL"

export const DELETE_SINGLE_USER = "DELETE_SINGLE_USER"
export const DELETE_SINGLE_USER_SUCCESS = "DELETE_SINGLE_USER_SUCCESS"
export const DELETE_SINGLE_USER_FAIL = "DELETE_SINGLE_USER_FAIL"


export const LOGOUT = "LOGOUT"